In [36]:
import pandas as pd 
import numpy as np 
import re
import json 
import requests
from io import StringIO

In [26]:
ticker = "AAPL"
start_date = "2020-02-17"
end_date = "2022-02-17"
key = "JNXjDfnAXrs5h2xWCz3tlw7KBr5_TKaq"
link = f"https://api.polygon.io/v2/aggs/ticker/{ticker}/range/1/day/{start_date}/{end_date}?apiKey={key}"

In [32]:
response = requests.get(link)

In [51]:
df = pd.read_json(json.dumps(response.json()["results"]))
column_key = {"c": "close_price", 
              "h": "high_price", 
              "l": "low_price", 
              "n": "num_transactions", 
              "o": "open_price", 
              "t": "time", 
              "v": "volume", 
              "vw": "volume_weighted_avg"}
df = df.rename(column_key, axis = 1)
df["time"] = pd.to_datetime(df["time"], unit = "ms")
df["ticker"] = ticker
df

,volume,volume_weighted_avg,open_price,close_price,high_price,low_price,time,num_transactions,ticker
0,93983964,80.7971,80.0000,80.9050,81.1425,80.0000,2020-02-19 05:00:00,205432,AAPL
1,100565956,80.2818,80.6575,80.0750,81.1625,79.5525,2020-02-20 05:00:00,243574,AAPL
2,129705660,78.6341,79.6550,78.2625,80.1125,77.6250,2020-02-21 05:00:00,323163,AAPL
3,222149312,74.8699,74.3150,74.5450,76.0450,72.3075,2020-02-24 05:00:00,586879,AAPL
4,230623456,73.3055,75.2375,72.0200,75.6325,71.5325,2020-02-25 05:00:00,624788,AAPL
...,...,...,...,...,...,...,...,...,...
501,98490687,170.1997,172.3300,168.6400,173.0800,168.0400,2022-02-11 05:00:00,815714,AAPL
502,86185530,168.3917,167.3700,168.8800,169.5800,166.5600,2022-02-14 05:00:00,757491,AAPL
503,64286317,171.6596,170.9700,172.7900,172.9500,170.2500,2022-02-15 05:00:00,562851,AAPL
504,61139697,171.6489,171.8500,172.5500,173.3400,170.0500,2022-02-16 05:00:00,543032,AAPL
505,69589344,170.1812,171.0300,168.8800,171.9100,168.4700,2022-02-17 05:00:00,584118,AAPL

In [74]:
stocks = pd.read_csv("nasdaq.csv")
symbols = list(stocks.sort_values(by = "Market Cap", ascending = False)["Symbol"][:200])
rand = list(np.random.choice(stocks[~stocks.Symbol.isin(top_200)]["Symbol"], 800))
symbols += rand

In [76]:
len(symbols)

1000